import React, { useEffect, useMemo, useState } from 'react';

const fields = [
  ['status','CRM status'],['acquisition.firstSource','First acquisition source'],['acquisition.latestSource','Latest acquisition source'],['hasReferrer','Has referrer'],['tag','CRM tag'],['stage','Pipeline stage'],['assignedOwner','CRM owner'],['region','Region'],['preferredLanguage','Preferred language'],['hasVerifiedLineIdentity','Verified LINE'],['followUp.overdue','Overdue follow-up'],['followUp.hasOpen','Open follow-up'],['trait.zodiac','Zodiac'],['createdAt','Created at'],['updatedAt','Updated at'],
];
const boolFields=new Set(['hasReferrer','hasVerifiedLineIdentity','followUp.overdue','followUp.hasOpen']);
const dateFields=new Set(['createdAt','updatedAt']);
const sourceTypes=['LINE_ORGANIC','KEYWORD','RICH_MENU','QR','LINE_SHARE','REFERRAL_SHARE','PERSONAL_CARD_SHARE','EVENT','CSV_IMPORT','XLSX_IMPORT','OCR_IMPORT','API_IMPORT'];
const zodiac=['ARIES','TAURUS','GEMINI','CANCER','LEO','VIRGO','LIBRA','SCORPIO','SAGITTARIUS','CAPRICORN','AQUARIUS','PISCES'];
const safeApi=async(request,path,options)=>{const res=await request(path,options);const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'REQUEST_FAILED');return data;};
const blank=()=>({field:'status',op:'EQ',value:'ACTIVE'});
const ops=(field)=>boolFields.has(field)?['IS_TRUE','IS_FALSE']:dateFields.has(field)?['BEFORE','AFTER']:['EQ','NEQ','IN','NOT_IN'];
const normalized=(conditions)=>({operator:'AND',conditions:conditions.map(c=>boolFields.has(c.field)?{field:c.field,op:c.op}:{field:c.field,op:c.op,value:['IN','NOT_IN'].includes(c.op)?String(c.value||'').split(',').map(x=>x.trim()).filter(Boolean):String(c.value||'')})});
const errorText=(error)=>({CRM_SEGMENT_RULE_INVALID:'Rule must use AND with at most 20 conditions.',CRM_SEGMENT_RULE_CONDITION_INVALID:'Unsupported condition.',CRM_SEGMENT_RULE_VALUE_INVALID:'Provide a valid condition value.',CRM_SEGMENT_REFERENCE_INVALID:'The selected CRM reference is unavailable.',CRM_SEGMENT_ASSIGNED_OWNER_INVALID:'The selected CRM owner is unavailable.'}[error]||'Unable to complete this segment request.');
const Bar=({label,count})=><div className="space-y-1"><div className="flex justify-between gap-3 text-sm"><span className="truncate">{label||'Unassigned'}</span><b>{Number(count||0)}</b></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-slate-700" style={{width:`${Math.min(100,Math.max(4,Number(count||0)*8))}%`}} /></div></div>;

export default function CrmAnalyticsPanel({request,userRole='viewer'}){
 const role=String(userRole).toLowerCase(), canManage=['owner','admin'].includes(role);
 const [period,setPeriod]=useState('30d'),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[analyticsError,setAnalyticsError]=useState('');
 const [conditions,setConditions]=useState([blank()]),[references,setReferences]=useState({tags:[],stages:[],owners:[]}),[preview,setPreview]=useState(null),[previewError,setPreviewError]=useState(''),[previewing,setPreviewing]=useState(false);
 const [segments,setSegments]=useState([]),[selected,setSelected]=useState(null),[people,setPeople]=useState([]),[nextCursor,setNextCursor]=useState(null),[segmentBusy,setSegmentBusy]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState('');
 const rule=useMemo(()=>normalized(conditions),[conditions]);
 const loadSummary=async()=>{setLoading(true);try{setSummary(await safeApi(request,`/api/crm/analytics-summary?period=${period}`));setAnalyticsError('');}catch(e){setAnalyticsError(e.message)}finally{setLoading(false)}};
 const loadSegments=async()=>{try{const data=await safeApi(request,'/api/crm/segments');setSegments(data.segments||[])}catch(e){setAnalyticsError(e.message)}};
 // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void loadSummary()},[period]); // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void loadSegments();safeApi(request,'/api/crm/tags').then(x=>setReferences(v=>({...v,tags:x.tags||[]}))).catch(()=>{});safeApi(request,'/api/crm/pipeline-stages').then(x=>setReferences(v=>({...v,stages:x.stages||[]}))).catch(()=>{});safeApi(request,'/api/crm/assignees').then(x=>setReferences(v=>({...v,owners:x.assignees||[]}))).catch(()=>{});},[]);
 const update=(index,patch)=>setConditions(all=>all.map((c,i)=>i===index?{...c,...patch}:c));
 const values=(field)=>field==='tag'?references.tags.map(x=>[x.safeTagReference||x.tagReference,x.name||x.label]):field==='stage'?references.stages.map(x=>[x.stageReference,x.name||x.stageLabel]):field==='assignedOwner'?references.owners.map(x=>[x.assignedUserReference,x.displayLabel]):field.startsWith('acquisition.')?sourceTypes.map(x=>[x,x]):field==='trait.zodiac'?zodiac.map(x=>[x,x]):[];
 const runPreview=async()=>{setPreviewing(true);setPreviewError('');try{setPreview(await safeApi(request,'/api/crm/segments/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rule})}))}catch(e){setPreview(null);setPreviewError(errorText(e.message))}finally{setPreviewing(false)}};
 const save=async(edit=false)=>{if(!canManage)return;setSegmentBusy(true);try{const path=edit?`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}`:'/api/crm/segments';const data=await safeApi(request,path,{method:edit?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name||selected?.name,description,rule})});setSelected(data.segment);await loadSegments()}catch(e){setPreviewError(errorText(e.message))}finally{setSegmentBusy(false)}};
 const openSegment=async(segment)=>{try{const data=await safeApi(request,`/api/crm/segments/${encodeURIComponent(segment.safeSegmentReference)}`);setSelected(data.segment);setName(data.segment.name||'');setDescription(data.segment.description||'');setConditions(data.segment.rule?.conditions||[blank()]);setPeople([]);setNextCursor(null)}catch(e){setPreviewError(errorText(e.message))}};
 const loadPeople=async(cursor='')=>{if(!selected)return;try{const path=`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}/people?limit=25${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`;const data=await safeApi(request,path);setPeople(existing=>cursor?[...existing,...(data.people||[])]:data.people||[]);setNextCursor(data.nextCursor||null)}catch(e){setPreviewError(errorText(e.message))}};
 const archive=async()=>{if(!selected||!canManage)return;setSegmentBusy(true);try{await safeApi(request,`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'ARCHIVED'})});await loadSegments();setSelected(x=>x?{...x,status:'ARCHIVED'}:x)}catch(e){setPreviewError(errorText(e.message))}finally{setSegmentBusy(false)}};
 const metrics=summary?[['CRM People',summary.totalPeople],['New people',summary.newPeopleInPeriod],['Verified LINE',summary.peopleWithLineIdentity],['No verified LINE',summary.peopleWithoutLineIdentity],['With referrer',summary.peopleWithReferrer],['Without referrer',summary.peopleWithoutReferrer],['Open follow-ups',summary.openFollowUpCount],['Overdue follow-ups',summary.overdueFollowUpCount]]:[];
 return <section data-testid="crm-analytics-panel" className="space-y-6">
  <header className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">CRM Analytics</h2><p className="text-sm text-gray-500">Read-only CRM distributions and live segments.</p></div><div className="flex gap-2"><button onClick={()=>setPeriod('7d')} className={`rounded px-3 py-2 text-sm ${period==='7d'?'bg-slate-800 text-white':'border'}`}>7d</button><button onClick={()=>setPeriod('30d')} className={`rounded px-3 py-2 text-sm ${period==='30d'?'bg-slate-800 text-white':'border'}`}>30d</button></div></header>
  {analyticsError&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">Analytics unavailable.</p>}
  {loading?<p>Loading analytics…</p>:summary&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map(([label,value])=><div key={label} className="rounded border bg-white p-4"><div className="text-xs text-gray-500">{label}</div><b className="text-2xl">{Number(value||0)}</b></div>)}</div><div className="grid gap-4 lg:grid-cols-2">{[['Stage distribution',summary.peopleByStage,'stageLabel'],['Latest acquisition source',summary.peopleByAcquisitionSource,'sourceType'],['Tag distribution',summary.peopleByTag,'tagLabel'],['Owner distribution',summary.peopleByAssignedOwner,'ownerLabel']].map(([title,rows,key])=><article key={title} className="rounded border bg-white p-4"><h3 className="font-semibold">{title}</h3><div className="mt-3 space-y-3">{rows.length?rows.map(row=><Bar key={row[key]} label={row[key]} count={row.count}/>):<p className="text-sm text-gray-500">No current data.</p>}</div></article>)}</div></>}
  <article className="rounded-xl border bg-white p-5"><h2 className="font-bold">Segment Builder</h2><p className="mt-1 text-sm text-gray-500">AND only. Live results use current CRM data; no audience snapshot is stored.</p><div className="mt-4 space-y-3">{conditions.map((condition,index)=><div key={index} className="grid gap-2 md:grid-cols-4"><select value={condition.field} onChange={e=>update(index,{field:e.target.value,op:ops(e.target.value)[0],value:''})} className="rounded border p-2">{fields.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={condition.op} onChange={e=>update(index,{op:e.target.value})} className="rounded border p-2">{ops(condition.field).map(op=><option key={op}>{op}</option>)}</select>{boolFields.has(condition.field)?<span className="rounded border bg-gray-50 p-2 text-sm">Boolean condition</span>:values(condition.field).length?<select value={condition.value||''} onChange={e=>update(index,{value:e.target.value})} className="rounded border p-2"><option value="">Select…</option>{values(condition.field).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input value={condition.value||''} onChange={e=>update(index,{value:e.target.value})} placeholder={dateFields.has(condition.field)?'ISO date':'Value'} className="rounded border p-2"/>}<button type="button" disabled={conditions.length===1} onClick={()=>setConditions(all=>all.filter((_,i)=>i!==index))} className="rounded border px-3 text-sm disabled:opacity-50">Remove</button></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={conditions.length>=20} onClick={()=>setConditions(all=>[...all,blank()])} className="rounded border px-3 py-2 text-sm disabled:opacity-50">Add condition</button><button type="button" onClick={runPreview} disabled={previewing} className="rounded bg-slate-800 px-3 py-2 text-sm text-white">{previewing?'Validating…':'Preview'}</button>{canManage&&<button type="button" onClick={()=>save(false)} disabled={segmentBusy||!name.trim()} className="rounded bg-blue-700 px-3 py-2 text-sm text-white">Save segment</button>}<input aria-label="Segment name" value={name} onChange={e=>setName(e.target.value)} placeholder="Segment name" className="rounded border p-2 text-sm"/></div>{previewError&&<p role="alert" className="mt-3 text-sm text-red-700">{previewError}</p>}{preview&&<div className="mt-4 rounded bg-slate-50 p-3 text-sm"><b>{preview.totalCount} people</b>{preview.truncated&&<p>Only the first 25 matching people are shown.</p>}<div className="mt-2 space-y-1">{(preview.previewPeople||[]).map((person,i)=><p key={person.personRef||i}>{person.profile?.contactName||person.profile?.displayName||'CRM Person'} {person.profile?.companyName||''}</p>)}</div></div>}</article>
  <div className="grid gap-4 lg:grid-cols-2"><article className="rounded border bg-white p-4"><h2 className="font-bold">Saved segments</h2><div className="mt-3 space-y-2">{segments.length?segments.map(segment=><button key={segment.safeSegmentReference} onClick={()=>openSegment(segment)} className="block w-full rounded border p-3 text-left hover:bg-gray-50"><b>{segment.name}</b><div className="text-xs text-gray-500">{segment.status} · v{segment.currentVersion}</div></button>):<p className="text-sm text-gray-500">No saved segments.</p>}</div></article>{selected&&<article className="rounded border bg-white p-4"><h2 className="font-bold">{selected.name}</h2><p className="mt-1 text-sm text-gray-500">Version {selected.currentVersion||selected.currentVersionNo} · {selected.status}</p><p className="mt-2 text-sm">Editing creates a new immutable version; history remains read-only.</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>loadPeople()} className="rounded bg-slate-800 px-3 py-2 text-sm text-white">Load live people</button>{canManage&&selected.status==='ACTIVE'&&<><button onClick={()=>save(true)} disabled={segmentBusy} className="rounded border px-3 py-2 text-sm">Save new version</button><button onClick={archive} disabled={segmentBusy} className="rounded border border-amber-300 px-3 py-2 text-sm text-amber-800">Archive segment</button></>}</div><div className="mt-3 space-y-1 text-sm">{(selected.versions||[]).map(v=><p key={v.version}>v{v.version} · {v.createdAt||''}</p>)}</div><p className="mt-3 text-xs text-gray-500">Live membership is calculated from current CRM data.</p><div className="mt-3 space-y-2">{people.map((person,i)=><p key={person.personRef||i} className="rounded bg-slate-50 p-2 text-sm">{person.profile?.contactName||person.profile?.displayName||'CRM Person'} {person.profile?.companyName||''}</p>)}{nextCursor&&<button onClick={()=>loadPeople(nextCursor)} className="rounded border px-3 py-2 text-sm">Load more</button>}</div></article>}</div>
 </section>;
}