import React, { useCallback, useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';

export default function LineIntelligenceHealthPanel({ request }) {
  const [state, setState] = useState({ loading: true, bindings: [], error: '' });
  const load = useCallback(async () => {
    setState(previous => ({ ...previous, loading: true, error: '' }));
    try { const response = await request('/api/system/line-intelligence/health'); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Unable to load intelligence health.'); setState({ loading: false, bindings: data.bindings || [], error: '' }); } catch (error) { setState({ loading: false, bindings: [], error: error.message || 'Unable to load intelligence health.' }); }
  }, [request]);
  useEffect(() => { load(); }, [load]);
  return <div className="space-y-5 animate-in fade-in duration-500"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold tracking-tight text-gray-900">LINE Intelligence Health</h2><p className="mt-1 text-sm text-gray-500">Platform-only cache health. This view never exposes workspace LINE tokens, UIDs, or raw event contents.</p></div><button type="button" onClick={load} className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-bold">Refresh</button></div>{state.loading && <div className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white p-8 text-sm text-gray-500"><Loader2 size={17} className="animate-spin" />Loading health...</div>}{state.error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{state.error}</div>}{!state.loading && !state.error && <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-sm"><table className="w-full text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="px-4 py-3 text-left">Workspace</th><th className="px-4 py-3 text-left">Project</th><th className="px-4 py-3 text-left">Menu</th><th className="px-4 py-3 text-left">Sync</th><th className="px-4 py-3 text-right">Cache rows</th><th className="px-4 py-3 text-right">Suppressed</th><th className="px-4 py-3 text-right">Unmatched</th></tr></thead><tbody className="divide-y divide-gray-100">{state.bindings.map(row => <tr key={`${row.workspaceId}-${row.projectId}-${row.lineRichMenuId}`}><td className="px-4 py-3">{row.workspaceId}</td><td className="px-4 py-3">{row.projectName || row.projectId}</td><td className="px-4 py-3 font-mono text-xs">{row.lineRichMenuId}</td><td className="px-4 py-3">{row.lastSyncStatus || row.status} {row.lastSyncedAt ? <span className="block text-xs text-gray-400">{row.lastSyncedAt}</span> : null}</td><td className="px-4 py-3 text-right">{Number(row.cachedRows || 0).toLocaleString('zh-TW')}</td><td className="px-4 py-3 text-right">{Number(row.privacyRows || 0).toLocaleString('zh-TW')}</td><td className="px-4 py-3 text-right">{Number(row.unmatchedRows || 0).toLocaleString('zh-TW')}</td></tr>)}{state.bindings.length === 0 && <tr><td colSpan="7" className="px-4 py-8 text-center text-gray-500">No linked Rich Menus yet.</td></tr>}</tbody></table></div>}</div>;
}
