import { executeMeteredAiCall, extractGeminiUsageMetadata } from '../ai/usage.ts';
import { GEMINI_MODEL, requestGeminiContent } from '../gemini.ts';
import { requireWorkspaceModule } from '../modules/entitlements.ts';
import { TRAVEL_PROMOTION_EXTRACT_SCHEMA, TRAVEL_PROMOTION_EXTRACTION_INSTRUCTION, activatePromotion, archivePromotion, createPromotion, extractionSource, listPromotions, parsePromotionAiPayload, readPromotion, saveExtractedDraft, updatePromotionDraft } from './promotion.ts';

const arrayBufferToBase64=(buffer:ArrayBuffer)=>{const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(binary)};
const exactAction=(value:unknown,fields:readonly string[])=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('TRAVEL_PROMOTION_INPUT_INVALID');const body=value as Record<string,unknown>;if(Object.keys(body).some(key=>!fields.includes(key)))throw new Error('TRAVEL_PROMOTION_INPUT_INVALID');return body};

export function registerTravelPromotionRoutes(app:any,deps:any,fail:(c:any,error:unknown,fallback:string)=>Response){
  app.get('/api/travel/promotions',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,promotions:await listPromotions(c.env.smart_menu_db,deps.workspaceIdOf(c))})}catch(e){return fail(c,e,'TRAVEL_PROMOTION_LIST_FAILED')}});
  app.post('/api/travel/promotions',async(c:any)=>{try{deps.requireRole(c,'admin');const promotion=await createPromotion(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,promotion},201)}catch(e){return fail(c,e,'TRAVEL_PROMOTION_CREATE_FAILED')}});
  app.get('/api/travel/promotions/:safePromotionReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,promotion:await readPromotion(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safePromotionReference'),100))})}catch(e){return fail(c,e,'TRAVEL_PROMOTION_READ_FAILED')}});
  app.patch('/api/travel/promotions/:safePromotionReference/draft',async(c:any)=>{try{deps.requireRole(c,'admin');const promotion=await updatePromotionDraft(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safePromotionReference'),100),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,promotion})}catch(e){return fail(c,e,'TRAVEL_PROMOTION_DRAFT_UPDATE_FAILED')}});
  app.post('/api/travel/promotions/:safePromotionReference/extract',async(c:any)=>{try{
    deps.requireRole(c,'admin');const workspaceId=deps.workspaceIdOf(c);
    try{await requireWorkspaceModule({db:c.env.smart_menu_db,workspaceId,moduleKey:'AI'})}catch(e){if(e instanceof Error&&['MODULE_NOT_ENABLED','MODULE_DEPENDENCY_NOT_ENABLED'].includes(e.message))throw new Error('TRAVEL_PROMOTION_AI_DISABLED');throw e}
    if(!c.env.GEMINI_API_KEY)throw new Error('TRAVEL_PROMOTION_AI_UNAVAILABLE');
    const body=exactAction(await c.req.json().catch(()=>({})),['expectedVersionNo','expectedSourceRevision']);const expectedVersionNo=Number(body.expectedVersionNo),expectedSourceRevision=Number(body.expectedSourceRevision);if(!Number.isInteger(expectedVersionNo)||expectedVersionNo<1||!Number.isInteger(expectedSourceRevision)||expectedSourceRevision<1)throw new Error('TRAVEL_PROMOTION_INPUT_INVALID');
    const reference=deps.text(c.req.param('safePromotionReference'),100);const source=await extractionSource(c.env.smart_menu_db,{workspaceId,reference,userId:deps.text(c.get('userId'))||null,expectedVersionNo,expectedSourceRevision});
    const parts:Array<Record<string,unknown>>=[{text:TRAVEL_PROMOTION_EXTRACTION_INSTRUCTION},{text:`Untrusted promotion source text begins:\n<source>${source.sourceText}</source>\nUntrusted source text ends.`}];let total=0;
    for(const asset of source.assets){const size=Number(asset.size_bytes||0);total+=size;if(size<1||size>1024*1024||total>5*1024*1024)throw new Error('TRAVEL_PROMOTION_ASSET_INVALID');const object=await c.env.smart_menu_assets.get(asset.storage_key);if(!object)throw new Error('TRAVEL_PROMOTION_ASSET_INVALID');parts.push({inline_data:{mime_type:asset.content_type,data:arrayBufferToBase64(await object.arrayBuffer())}})}
    let providerRequestId:string|null=null;const draft=await executeMeteredAiCall({db:c.env.smart_menu_db,workspaceId,userId:deps.text(c.get('userId'))||null,featureCode:'travel_promotion_extract',operationCode:`promotion_v${source.versionNo}_r${source.sourceRevision}`,provider:'google',model:GEMINI_MODEL,execute:async()=>{const response=await requestGeminiContent({apiKey:c.env.GEMINI_API_KEY,body:{contents:[{role:'user',parts}],generationConfig:{responseMimeType:'application/json',responseSchema:TRAVEL_PROMOTION_EXTRACT_SCHEMA}}});providerRequestId=response.headers.get('x-request-id');const payload=await response.json();if(!response.ok)return{value:null as never,status:'failed' as const,usage:extractGeminiUsageMetadata(payload),providerRequestId,errorCode:'TRAVEL_PROMOTION_AI_PROVIDER_FAILED'};return{value:parsePromotionAiPayload(payload),status:'success' as const,usage:extractGeminiUsageMetadata(payload),providerRequestId}}});
    if(!draft)throw new Error('TRAVEL_PROMOTION_AI_PROVIDER_FAILED');const promotion=await saveExtractedDraft(c.env.smart_menu_db,{workspaceId,reference,versionNo:source.versionNo,sourceRevision:source.sourceRevision,draft});return c.json({success:true,promotion});
  }catch(e){return fail(c,e,'TRAVEL_PROMOTION_AI_EXTRACT_FAILED')}});
  app.post('/api/travel/promotions/:safePromotionReference/activate',async(c:any)=>{try{deps.requireRole(c,'admin');const body=exactAction(await c.req.json().catch(()=>({})),['expectedVersionNo']);const expectedVersionNo=Number(body.expectedVersionNo);if(!Number.isInteger(expectedVersionNo)||expectedVersionNo<1)throw new Error('TRAVEL_PROMOTION_INPUT_INVALID');const promotion=await activatePromotion(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safePromotionReference'),100),userId:deps.text(c.get('userId'))||null,expectedVersionNo});return c.json({success:true,promotion})}catch(e){return fail(c,e,'TRAVEL_PROMOTION_ACTIVATE_FAILED')}});
  app.post('/api/travel/promotions/:safePromotionReference/archive',async(c:any)=>{try{deps.requireRole(c,'admin');exactAction(await c.req.json().catch(()=>({})),[]);const promotion=await archivePromotion(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safePromotionReference'),100)});return c.json({success:true,promotion})}catch(e){return fail(c,e,'TRAVEL_PROMOTION_ARCHIVE_FAILED')}});
}
