import { createDeparture, createItinerary, listBookingEvents, listBookings, listDepartures, listItineraries, readBooking, readDeparture, readItinerary, setDepartureStatus, transitionItinerary, updateDeparture, updateItinerary } from './travel';

const known = /^TRAVEL_[A-Z0-9_]+$/;
function fail(c:any,error:unknown,fallback:string){const raw=error instanceof Error?error.message:'';const code=raw==='FORBIDDEN_ROLE'?'FORBIDDEN':known.test(raw)?raw:fallback;const status=code==='FORBIDDEN'?403:code.endsWith('_NOT_FOUND')?404:code.includes('CAPACITY')||code.includes('TRANSITION')||code.includes('NOT_EDITABLE')||code.includes('ARCHIVED')?409:400;return c.json({success:false,error:code},status);}

export function registerTravelRoutes(app:any,deps:any){
  app.get('/api/travel/itineraries',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,itineraries:await listItineraries(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_LIST_FAILED')}});
  app.post('/api/travel/itineraries',async(c:any)=>{try{deps.requireRole(c,'admin');const itinerary=await createItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,itinerary},201);}catch(e){return fail(c,e,'TRAVEL_ITINERARY_CREATE_FAILED')}});
  app.get('/api/travel/itineraries/:safeItineraryReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,itinerary:await readItinerary(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeItineraryReference'),100))});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_READ_FAILED')}});
  app.patch('/api/travel/itineraries/:safeItineraryReference',async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,itinerary:await updateItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeItineraryReference'),100),body:await c.req.json().catch(()=>({}))})});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_UPDATE_FAILED')}});
  for(const [path,action,role] of [['submit-review','submit','admin'],['approve','approve','owner'],['reject','reject','owner'],['archive','archive','admin']] as const){app.post(`/api/travel/itineraries/:safeItineraryReference/${path}`,async(c:any)=>{try{deps.requireRole(c,role);const body=await c.req.json().catch(()=>({}));return c.json({success:true,itinerary:await transitionItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeItineraryReference'),100),action,userId:deps.text(c.get('userId'))||null,reviewNote:body.reviewNote})});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_TRANSITION_FAILED')}})}
  app.get('/api/travel/itineraries/:safeItineraryReference/departures',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,departures:await listDepartures(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeItineraryReference'),100))});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_LIST_FAILED')}});
  app.post('/api/travel/itineraries/:safeItineraryReference/departures',async(c:any)=>{try{deps.requireRole(c,'admin');const departure=await createDeparture(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),itineraryReference:deps.text(c.req.param('safeItineraryReference'),100),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,departure},201);}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_CREATE_FAILED')}});
  app.get('/api/travel/departures/:safeDepartureReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,departure:await readDeparture(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeDepartureReference'),100))});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_READ_FAILED')}});
  app.patch('/api/travel/departures/:safeDepartureReference',async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,departure:await updateDeparture(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeDepartureReference'),100),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_UPDATE_FAILED')}});
  for(const action of ['open','close','cancel','archive'] as const){app.post(`/api/travel/departures/:safeDepartureReference/${action}`,async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,departure:await setDepartureStatus(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeDepartureReference'),100),action,userId:deps.text(c.get('userId'))||null})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_TRANSITION_FAILED')}})}
  app.get('/api/travel/bookings',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,bookings:await listBookings(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)})});}catch(e){return fail(c,e,'TRAVEL_BOOKING_LIST_FAILED')}});
  app.get('/api/travel/bookings/:safeBookingReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,booking:await readBooking(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)},deps.text(c.req.param('safeBookingReference'),100))});}catch(e){return fail(c,e,'TRAVEL_BOOKING_READ_FAILED')}});
  app.get('/api/travel/bookings/:safeBookingReference/events',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,events:await listBookingEvents(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)},deps.text(c.req.param('safeBookingReference'),100))});}catch(e){return fail(c,e,'TRAVEL_BOOKING_EVENTS_READ_FAILED')}});
}
